# -*- coding: utf-8 -*-

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *
from utils import *


class Ui_Snail_PP(QWidget):
    def setupUi(self, Snail_PP):
        if not Snail_PP.objectName():
            Snail_PP.setObjectName("Snail_PP")
        Snail_PP.setWindowModality(Qt.NonModal)
        Snail_PP.resize(891, 780)
        font = QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        Snail_PP.setFont(font)
        Snail_PP.setAutoFillBackground(False)
        Snail_PP.setStyleSheet(
            "QWidget{background-color: rgb(35, 35, 39);}\n" "*:hover {color: rgb(255, 191, 0);}"
        )
        self.verticalLayout_2 = QVBoxLayout(Snail_PP)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.v0 = QHBoxLayout()
        self.v0.setObjectName("v0")
        self.v0.setContentsMargins(-1, 0, -1, 0)
        self.cb_cacheNode = QCheckBox(Snail_PP)
        self.cb_cacheNode.setObjectName("cb_cacheNode")
        font1 = QFont()
        font1.setFamily("Microsoft YaHei UI")
        font1.setPointSize(11)
        font1.setBold(False)
        font1.setItalic(False)
        font1.setWeight(50)
        self.cb_cacheNode.setFont(font1)
        self.cb_cacheNode.setStyleSheet("color:rgb(255, 170, 0);")
        self.cb_cacheNode.setInputMethodHints(Qt.ImhNone)
        self.cb_cacheNode.setText("Cache node")
        self.cb_cacheNode.setChecked(True)
        self.cb_cacheNode.setTristate(False)

        self.v0.addWidget(self.cb_cacheNode)

        self.cb_renderNode = QCheckBox(Snail_PP)
        self.cb_renderNode.setObjectName("cb_renderNode")
        self.cb_renderNode.setFont(font1)
        self.cb_renderNode.setStyleSheet("color: rgb(150, 104, 236);")
        self.cb_renderNode.setText("Render node")
        self.cb_renderNode.setChecked(False)

        self.v0.addWidget(self.cb_renderNode)

        self.cb_soloNonlocal = QCheckBox(Snail_PP)
        self.cb_soloNonlocal.setObjectName("cb_soloNonlocal")
        self.cb_soloNonlocal.setFont(font1)
        self.cb_soloNonlocal.setStyleSheet("color: rgb(85, 170, 255);")
        self.cb_soloNonlocal.setText("Solo non local")

        self.v0.addWidget(self.cb_soloNonlocal)

        self.cb_soloError = QCheckBox(Snail_PP)
        self.cb_soloError.setObjectName("cb_soloError")
        self.cb_soloError.setFont(font1)
        self.cb_soloError.setStyleSheet("color: rgb(231, 93, 99);")
        self.cb_soloError.setText("Sole error")

        self.v0.addWidget(self.cb_soloError)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.v0.addItem(self.horizontalSpacer)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.v0.addLayout(self.horizontalLayout_2)

        self.verticalLayout_2.addLayout(self.v0)

        self.w_search = QWidget(Snail_PP)
        self.w_search.setObjectName("w_search")
        self.horizontalLayout = QHBoxLayout(self.w_search)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.v4 = QHBoxLayout()
        self.v4.setObjectName("v4")
        self.v4.setContentsMargins(8, 0, 8, -1)

        self.horizontalLayout.addLayout(self.v4)

        self.verticalLayout_2.addWidget(self.w_search)

        self.v1 = QVBoxLayout()
        self.v1.setSpacing(0)
        self.v1.setObjectName("v1")
        self.v1.setContentsMargins(-1, 0, -1, -1)
        self.splitter_h = QSplitter(Snail_PP)
        self.splitter_h.setObjectName("splitter_h")
        self.splitter_h.setMinimumSize(QSize(0, 30))
        self.splitter_h.setOrientation(Qt.Horizontal)
        self.verticalLayoutWidget_3 = QWidget(self.splitter_h)
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_7 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.splitter_v = QSplitter(self.verticalLayoutWidget_3)
        self.splitter_v.setObjectName("splitter_v")
        self.splitter_v.setStyleSheet("QListWidget {background-color: rgba(0,0,0,0);}")
        self.splitter_v.setOrientation(Qt.Vertical)
        self.verticalLayoutWidget_5 = QWidget(self.splitter_v)
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_9 = QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_3.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.tableWidget = QTableWidget(self.verticalLayoutWidget_5)
        if self.tableWidget.columnCount() < 4:
            self.tableWidget.setColumnCount(4)
        font2 = QFont()
        font2.setFamily("Microsoft YaHei UI")
        font2.setPointSize(10)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setText("File path")
        __qtablewidgetitem.setFont(font2)
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setText("Node")
        __qtablewidgetitem1.setFont(font2)
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setText("Class")
        __qtablewidgetitem2.setFont(font2)
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        __qtablewidgetitem3.setText("State")
        __qtablewidgetitem3.setFont(font2)
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        if self.tableWidget.rowCount() < 3:
            self.tableWidget.setRowCount(3)
        __qtablewidgetitem4 = QTableWidgetItem()
        __qtablewidgetitem4.setText("1")
        self.tableWidget.setVerticalHeaderItem(0, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        __qtablewidgetitem5.setText("2")
        self.tableWidget.setVerticalHeaderItem(1, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        __qtablewidgetitem6.setText("3")
        self.tableWidget.setVerticalHeaderItem(2, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        __qtablewidgetitem7.setText("/mat/principledMaterial")
        self.tableWidget.setItem(0, 0, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget.setItem(0, 1, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        __qtablewidgetitem9.setText("albedo")
        self.tableWidget.setItem(0, 2, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.tableWidget.setItem(0, 3, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        __qtablewidgetitem11.setText("/obj/geo/filecache1")
        self.tableWidget.setItem(1, 0, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.tableWidget.setItem(1, 1, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        __qtablewidgetitem13.setText("file")
        self.tableWidget.setItem(1, 2, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.tableWidget.setItem(1, 3, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        __qtablewidgetitem15.setText("obj/geo2/file1")
        self.tableWidget.setItem(2, 0, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.tableWidget.setItem(2, 1, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        __qtablewidgetitem17.setText("file")
        self.tableWidget.setItem(2, 2, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.tableWidget.setItem(2, 3, __qtablewidgetitem18)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setFont(font)
        self.tableWidget.setContextMenuPolicy(Qt.CustomContextMenu)
        self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(Qt.ElideMiddle)
        self.tableWidget.setVerticalScrollMode(QAbstractItemView.ScrollPerItem)
        self.tableWidget.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(Qt.NoPen)
        self.tableWidget.setSortingEnabled(True)
        self.tableWidget.setWordWrap(False)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(50)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(125)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(25)
        self.tableWidget.verticalHeader().setDefaultSectionSize(28)

        self.verticalLayout_3.addWidget(self.tableWidget)

        self.verticalLayout_9.addLayout(self.verticalLayout_3)

        self.splitter_v.addWidget(self.verticalLayoutWidget_5)
        self.verticalLayoutWidget_6 = QWidget(self.splitter_v)
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_10 = QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.layout_v = QVBoxLayout()
        self.layout_v.setObjectName("layout_v")
        self.layout_v.setContentsMargins(-1, 0, -1, -1)
        self.splitter = QSplitter(self.verticalLayoutWidget_6)
        self.splitter.setObjectName("splitter")
        self.splitter.setMinimumSize(QSize(0, 0))
        self.splitter.setMaximumSize(QSize(16777215, 16777215))
        self.splitter.setOrientation(Qt.Horizontal)
        self.splitter.setChildrenCollapsible(True)
        self.gb_info = QGroupBox(self.splitter)
        self.gb_info.setObjectName("gb_info")
        sizePolicy = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_info.sizePolicy().hasHeightForWidth())
        self.gb_info.setSizePolicy(sizePolicy)
        self.gb_info.setMinimumSize(QSize(0, 0))
        font3 = QFont()
        font3.setFamily("Microsoft YaHei UI")
        self.gb_info.setFont(font3)
        self.gb_info.setLocale(QLocale(QLocale.Chinese, QLocale.China))
        self.gb_info.setTitle("Info")
        self.horizontalLayout_15 = QHBoxLayout(self.gb_info)
        self.horizontalLayout_15.setSpacing(2)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_15.setContentsMargins(2, 6, 2, 2)
        self.scrollArea_5 = QScrollArea(self.gb_info)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollArea_5.setStyleSheet("border: none;")
        self.scrollArea_5.setLocale(QLocale(QLocale.Chinese, QLocale.China))
        self.scrollArea_5.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scrollArea_5.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scrollArea_5.setWidgetResizable(True)
        self.w_info = QWidget()
        self.w_info.setObjectName("w_info")
        self.w_info.setGeometry(QRect(0, 0, 427, 195))
        self.w_info.setStyleSheet("")
        self.verticalLayout_11 = QVBoxLayout(self.w_info)
        self.verticalLayout_11.setSpacing(4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(4, 4, 4, 4)
        self.layout_info = QVBoxLayout()
        self.layout_info.setSpacing(4)
        self.layout_info.setObjectName("layout_info")
        self.layout_info.setContentsMargins(0, 0, 0, 0)

        self.verticalLayout_11.addLayout(self.layout_info)

        self.scrollArea_5.setWidget(self.w_info)

        self.horizontalLayout_15.addWidget(self.scrollArea_5)

        self.splitter.addWidget(self.gb_info)
        self.gb_asset = QGroupBox(self.splitter)
        self.gb_asset.setObjectName("gb_asset")
        sizePolicy.setHeightForWidth(self.gb_asset.sizePolicy().hasHeightForWidth())
        self.gb_asset.setSizePolicy(sizePolicy)
        self.gb_asset.setMinimumSize(QSize(0, 0))
        self.gb_asset.setFont(font3)
        self.gb_asset.setLocale(QLocale(QLocale.Chinese, QLocale.China))
        self.gb_asset.setTitle("Assets")
        self.horizontalLayout_16 = QHBoxLayout(self.gb_asset)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.horizontalLayout_16.setContentsMargins(2, 6, 2, 2)
        self.scrollArea_6 = QScrollArea(self.gb_asset)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollArea_6.setStyleSheet("border: none;;")
        self.scrollArea_6.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scrollArea_6.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scrollArea_6.setWidgetResizable(True)
        self.w_asset = QWidget()
        self.w_asset.setObjectName("w_asset")
        self.w_asset.setGeometry(QRect(0, 0, 427, 195))
        self.w_asset.setAutoFillBackground(False)
        self.w_asset.setStyleSheet("")
        self.verticalLayout_13 = QVBoxLayout(self.w_asset)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.layout_asset = QVBoxLayout()
        self.layout_asset.setObjectName("layout_asset")

        self.verticalLayout_13.addLayout(self.layout_asset)

        self.scrollArea_6.setWidget(self.w_asset)

        self.horizontalLayout_16.addWidget(self.scrollArea_6)

        self.splitter.addWidget(self.gb_asset)

        self.layout_v.addWidget(self.splitter)

        self.verticalLayout_10.addLayout(self.layout_v)

        self.splitter_v.addWidget(self.verticalLayoutWidget_6)

        self.verticalLayout_7.addWidget(self.splitter_v)

        self.splitter_h.addWidget(self.verticalLayoutWidget_3)
        self.horizontalLayoutWidget_3 = QWidget(self.splitter_h)
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.layout_h = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.layout_h.setSpacing(0)
        self.layout_h.setObjectName("layout_h")
        self.layout_h.setContentsMargins(0, 0, 0, 0)
        self.splitter_h.addWidget(self.horizontalLayoutWidget_3)

        self.v1.addWidget(self.splitter_h)

        self.v1.setStretch(0, 1)

        self.verticalLayout_2.addLayout(self.v1)

        self.v2 = QHBoxLayout()
        self.v2.setObjectName("v2")
        self.v2.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.v2.setContentsMargins(8, 0, 8, -1)
        self.checkBox_1 = QCheckBox(Snail_PP)
        self.checkBox_1.setObjectName("checkBox_1")
        self.checkBox_1.setFont(font1)
        self.checkBox_1.setText("Format_01")
        self.checkBox_1.setChecked(True)

        self.v2.addWidget(self.checkBox_1)

        self.checkBox_2 = QCheckBox(Snail_PP)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_2.setFont(font1)
        self.checkBox_2.setText("Format_02")
        self.checkBox_2.setChecked(True)

        self.v2.addWidget(self.checkBox_2)

        self.checkBox_3 = QCheckBox(Snail_PP)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_3.setFont(font1)
        self.checkBox_3.setText("Format_03")
        self.checkBox_3.setChecked(True)

        self.v2.addWidget(self.checkBox_3)

        self.checkBox_4 = QCheckBox(Snail_PP)
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_4.setFont(font1)
        self.checkBox_4.setText("Format_04")
        self.checkBox_4.setChecked(True)

        self.v2.addWidget(self.checkBox_4)

        self.checkBox_5 = QCheckBox(Snail_PP)
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_5.setFont(font1)
        self.checkBox_5.setText("Format_05")
        self.checkBox_5.setChecked(True)

        self.v2.addWidget(self.checkBox_5)

        self.checkBox_6 = QCheckBox(Snail_PP)
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_6.setFont(font1)
        self.checkBox_6.setText("Format_06")
        self.checkBox_6.setChecked(True)

        self.v2.addWidget(self.checkBox_6)

        self.checkBox_7 = QCheckBox(Snail_PP)
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_7.setFont(font1)
        self.checkBox_7.setText("Format_07")
        self.checkBox_7.setChecked(True)

        self.v2.addWidget(self.checkBox_7)

        self.verticalLayout_2.addLayout(self.v2)

        self.line = QFrame(Snail_PP)
        self.line.setObjectName("line")
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)

        self.verticalLayout_2.addWidget(self.line)

        self.v5 = QHBoxLayout()
        self.v5.setObjectName("v5")
        self.v5.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.v5.setContentsMargins(8, 0, 8, -1)
        self.p_Path = QLabel(Snail_PP)
        self.p_Path.setObjectName("p_Path")
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.p_Path.sizePolicy().hasHeightForWidth())
        self.p_Path.setSizePolicy(sizePolicy1)
        self.p_Path.setMaximumSize(QSize(80, 16777215))
        self.p_Path.setFont(font)
        self.p_Path.setText("Path:")

        self.v5.addWidget(self.p_Path)

        self.label_5 = QLabel(Snail_PP)
        self.label_5.setObjectName("label_5")
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy2)
        self.label_5.setMinimumSize(QSize(400, 0))
        self.label_5.setSizeIncrement(QSize(336, 0))
        self.label_5.setBaseSize(QSize(336, 0))
        font4 = QFont()
        font4.setFamily("Microsoft YaHei UI")
        font4.setPointSize(8)
        self.label_5.setFont(font4)
        self.label_5.setStyleSheet("")
        self.label_5.setFrameShape(QFrame.NoFrame)
        self.label_5.setText("label_5")
        self.label_5.setMargin(0)

        self.v5.addWidget(self.label_5)

        self.radioButton_2 = QRadioButton(Snail_PP)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_2.setMinimumSize(QSize(0, 0))
        self.radioButton_2.setMaximumSize(QSize(50, 16777215))
        self.radioButton_2.setFont(font)
        self.radioButton_2.setAcceptDrops(False)
        self.radioButton_2.setAutoFillBackground(False)
        self.radioButton_2.setText("HIP")
        self.radioButton_2.setChecked(True)

        self.v5.addWidget(self.radioButton_2)

        self.radioButton = QRadioButton(Snail_PP)
        self.radioButton.setObjectName("radioButton")
        self.radioButton.setMinimumSize(QSize(0, 0))
        self.radioButton.setMaximumSize(QSize(50, 16777215))
        self.radioButton.setFont(font)
        self.radioButton.setText("JOB")

        self.v5.addWidget(self.radioButton)

        self.verticalLayout_2.addLayout(self.v5)

        self.line_3 = QFrame(Snail_PP)
        self.line_3.setObjectName("line_3")
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)

        self.verticalLayout_2.addWidget(self.line_3)

        self.v6 = QHBoxLayout()
        self.v6.setObjectName("v6")
        self.v6.setContentsMargins(8, 0, 8, -1)

        self.verticalLayout_2.addLayout(self.v6)

        QMetaObject.connectSlotsByName(Snail_PP)


class Ui_Dialog(QDialog):
    def __init__(self):
        super().__init__()
        self.setWindowIcon(QtGui.QIcon(ALLSET.sbox_path + "/file/icon01/SnailBox.svg"))
        self.setWindowTitle("SnailBox Assets Settings")
        self.setStyleSheet("*{background-color: rgb(35, 35, 39);}")
        self.resize(500, 300)
        self.setWindowFlags(self.windowFlags() & ~QtCore.Qt.WindowContextHelpButtonHint)

        layout = QVBoxLayout()
        self.tip_2 = Snail_Label("File formats separated by spaces, lowercase")
        self.tip_2.setFixedHeight(25)
        layout.addWidget(self.tip_2)

        for i in range(7):
            layout_1a = QHBoxLayout()
            layout_1b = QHBoxLayout()
            label_1 = Snail_LabelA(f"Class {i+1}")
            class_1 = Snail_LineEdit()
            class_1.setFixedWidth(200)
            format_1 = Snail_LineEdit()

            setattr(self, f"class_{i+1}", class_1)
            setattr(self, f"format_{i+1}", format_1)
            layout_1a.addWidget(label_1)
            layout_1a.addWidget(class_1)
            layout_1b.addWidget(format_1)
            if i == 0:
                self.tip_1 = Snail_Label("Categorized folder name")
                self.tip_1.setFixedHeight(25)
                layout_1a.addWidget(self.tip_1)
            else:
                spacer = QSpacerItem(0, 0, QSizePolicy.Expanding, QSizePolicy.Minimum)
                layout_1a.addItem(spacer)

            layout.addLayout(layout_1a)
            layout.addLayout(layout_1b)
            layout.addWidget(Snail_line())

        self.cb_1 = Snail_CheckBox("Ignore Cache nodes that are not activated Load from Disk.")
        self.cb_2 = Snail_CheckBox("Ignore Bypass nodes.")
        self.cb_3 = Snail_CheckBox("Ignore locked HDA nodes.")
        self.cb_4 = Snail_CheckBox("Package all preview image files.")
        layout.addWidget(self.cb_1)
        layout.addWidget(self.cb_2)
        layout.addWidget(self.cb_3)
        layout.addWidget(self.cb_4)
        layout.addWidget(Snail_line())

        layout_3 = QHBoxLayout()
        self.btn_2 = Snail_Btn("Cancel")
        self.btn_2.clicked.connect(self.close)
        self.btn_1 = Snail_Btn("Save")
        layout_3.addWidget(self.btn_2)
        layout_3.addWidget(self.btn_1)
        layout.addLayout(layout_3)

        self.setLayout(layout)
        # 设置对话框为模态窗口
        self.setModal(True)
